### ISSUE TITLE
[warn] Proxy Client: unable to connect to x.x.x.x:18193 ("general SOCKS server failure")

### ISSUE THREAD

**Issue by tj13** [Yawning/obfs4#19]
Hi,

tried to use obfs4 as transport proxy. but the client always failed with error "general SOCKS server failure". 

i'll really appreciate for your help.

Client configuration:
SOCKSListenAddress 0.0.0.0:9056
MaxCircuitDirtiness 10
UseBridges 1
#Log debug stderr
ClientTransportPlugin obfs4 exec /bin/obfs4proxy managed
#ClientTransportPlugin obfs4,obfs3 exec /bin/obfs4proxy managed
Bridge obfs4 x.x.x.x:18193 83E76FB30BE550FFFB2EFD53F0D5513FBB757375

Client log:

Jan 21 13:00:28.204 [notice] Tor v0.2.8.0-alpha-dev (git-7b6d7aae09ae2fe1) running on Linux with Libevent 2.0.21-stable, OpenSSL 1.0.1f and Zlib 1.2.8.
Jan 21 13:00:28.204 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jan 21 13:00:28.204 [notice] This version is not a stable Tor release. Expect more bugs than usual.
Jan 21 13:00:28.205 [notice] Read configuration file "/etc/torrc".
Jan 21 13:00:28.207 [warn] You specified a public address '0.0.0.0:9056' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
Jan 21 13:00:28.208 [warn] You specified a public address '0.0.0.0:9056' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
Jan 21 13:00:28.208 [notice] Opening Socks listener on 0.0.0.0:9056
Jan 21 13:00:28.000 [notice] Parsing GEOIP IPv4 file /usr/local/share/tor/geoip.
Jan 21 13:00:28.000 [notice] Parsing GEOIP IPv6 file /usr/local/share/tor/geoip6.
Jan 21 13:00:28.000 [warn] You are running Tor as root. You don't need to, and you probably shouldn't.
Jan 21 13:00:28.000 [notice] Bootstrapped 0%: Starting
Jan 21 13:00:28.000 [notice] Delaying directory fetches: No running bridges
Jan 21 13:00:30.000 [notice] Bootstrapped 5%: Connecting to directory server
Jan 21 13:00:30.000 [notice] Bootstrapped 10%: Finishing handshake with directory server
Jan 21 13:00:30.000 [warn] Proxy Client: unable to connect to x.x.x.x:18193 ("general SOCKS server failure")
Jan 21 13:02:32.603 [notice] Tor v0.2.8.0-alpha-dev (git-7b6d7aae09ae2fe1) running on Linux with Libevent 2.0.21-stable, OpenSSL 1.0.1f and Zlib 1.2.8.
Jan 21 13:02:32.603 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jan 21 13:02:32.603 [notice] This version is not a stable Tor release. Expect more bugs than usual.
Jan 21 13:02:32.603 [notice] Read configuration file "/etc/torrc".
Jan 21 13:02:32.605 [warn] You specified a public address '0.0.0.0:9056' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
Jan 21 13:02:32.606 [warn] You specified a public address '0.0.0.0:9056' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
Jan 21 13:02:32.606 [notice] Opening Socks listener on 0.0.0.0:9056
Jan 21 13:02:32.000 [notice] Parsing GEOIP IPv4 file /usr/local/share/tor/geoip.
Jan 21 13:02:32.000 [notice] Parsing GEOIP IPv6 file /usr/local/share/tor/geoip6.
Jan 21 13:02:32.000 [warn] You are running Tor as root. You don't need to, and you probably shouldn't.
Jan 21 13:02:32.000 [notice] Bootstrapped 0%: Starting
Jan 21 13:02:32.000 [notice] Delaying directory fetches: No running bridges
Jan 21 13:02:34.000 [notice] Bootstrapped 5%: Connecting to directory server
Jan 21 13:02:34.000 [notice] Bootstrapped 10%: Finishing handshake with directory server
Jan 21 13:02:34.000 [warn] Proxy Client: unable to connect to x.x.x.:18193 ("general SOCKS server failure")
Jan 21 13:17:34.000 [warn] Proxy Client: unable to connect to x.x.x.x:18193 ("general SOCKS server failure")
Jan 21 13:32:34.000 [warn] Proxy Client: unable to connect to x.x.x.x:18193 ("general SOCKS server failure")

Bridge configuration:
SocksPort 0
ORPort 9050 
BridgeRelay 1
Exitpolicy reject *:*
Nickname xxxyyyxxxyyy
ServerTransportPlugin obfs4,obfs3 exec /bin/obfs4proxy
ServerTransportListenAddr obfs4 0.0.0.0:18181
ServerTransportListenAddr obfs3 0.0.0.0:18182

ExtORPort auto

Bridge log:
Jan 21 12:51:57.443 [notice] Tor v0.2.8.0-alpha-dev (git-7b6d7aae09ae2fe1) running on Linux with Libevent 2.0.21-stable, OpenSSL 1.0.1f and Zlib 1.2.8.
Jan 21 12:51:57.444 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jan 21 12:51:57.444 [notice] This version is not a stable Tor release. Expect more bugs than usual.
Jan 21 12:51:57.444 [notice] Read configuration file "/etc/torrc".
Jan 21 12:51:57.447 [notice] Your ContactInfo config option is not set. Please consider setting it, so we can contact you if your server is misconfigured or something else goes wrong.
Jan 21 12:51:57.451 [notice] Based on detected system memory, MaxMemInQueues is set to 743 MB. You can override this by setting MaxMemInQueues by hand.
Jan 21 12:51:57.452 [notice] Opening OR listener on 0.0.0.0:9050
Jan 21 12:51:57.452 [notice] Opening Extended OR listener on 127.0.0.1:0
Jan 21 12:51:57.452 [notice] Extended OR listener listening on port 48828.
Jan 21 12:51:57.000 [notice] Parsing GEOIP IPv4 file /usr/local/share/tor/geoip.
Jan 21 12:51:57.000 [notice] Parsing GEOIP IPv6 file /usr/local/share/tor/geoip6.
Jan 21 12:51:57.000 [notice] Configured to measure statistics. Look for the *-stats files that will first be written to the data directory in 24 hours from now.
Jan 21 12:51:57.000 [warn] You are running Tor as root. You don't need to, and you probably shouldn't.
Jan 21 12:51:57.000 [notice] You are running a new relay. Thanks for helping the Tor network! If you wish to know what will happen in the upcoming weeks regarding its usage, have a look at https://blog.torproject.org/blog/lifecycle-of-a-new-relay
Jan 21 12:51:57.000 [notice] It looks like I need to generate and sign a new medium-term signing key, because I don't have one. To do that, I need to load (or create) the permanent master identity key.
Jan 21 12:51:58.000 [notice] Your Tor server's identity key fingerprint is 'xxxyyyxxxyyy 83E76FB30BE550FFFB2EFD53F0D5513FBB757375'
Jan 21 12:51:58.000 [notice] Your Tor bridge's hashed identity key fingerprint is 'xxxyyyxxxyyy 650CEBB969766129C5A1759B89F93AAF643608C8'
Jan 21 12:51:58.000 [notice] Bootstrapped 0%: Starting
Jan 21 12:51:58.000 [notice] Bootstrapped 5%: Connecting to directory server
Jan 21 12:51:58.000 [notice] Bootstrapped 10%: Finishing handshake with directory server
Jan 21 12:51:59.000 [notice] Registered server transport 'obfs4' at '[::]:18181'
Jan 21 12:51:59.000 [notice] Registered server transport 'obfs3' at '[::]:18182'
Jan 21 12:51:59.000 [notice] Bootstrapped 15%: Establishing an encrypted directory connection
Jan 21 12:51:59.000 [notice] Bootstrapped 20%: Asking for networkstatus consensus
Jan 21 12:51:59.000 [notice] Bootstrapped 50%: Loading relay descriptors
Jan 21 12:51:59.000 [notice] Guessed our IP address as 45.33.41.138 (source: 178.62.173.203).
Jan 21 12:52:00.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Jan 21 12:52:02.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 0/7108, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of exit bw = 0% of path bw.)
Jan 21 12:52:02.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 0/7108, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of exit bw = 0% of path bw.)
Jan 21 12:52:03.000 [notice] This version of Tor (0.2.8.0-alpha-dev) is newer than any recommended version, according to the directory authorities. Recommended versions are: 0.2.4.23,0.2.4.24,0.2.4.25,0.2.4.26,0.2.4.27,0.2.5.8-rc,0.2.5.9-rc,0.2.5.10,0.2.5.11,0.2.5.12,0.2.6.5-rc,0.2.6.6,0.2.6.7,0.2.6.8,0.2.6.9,0.2.6.10,0.2.7.1-alpha,0.2.7.2-alpha,0.2.7.3-rc,0.2.7.4-rc,0.2.7.5,0.2.7.6
Jan 21 12:52:03.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 0/7108, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of exit bw = 0% of path bw.)
Jan 21 12:52:03.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 500/7108, and can only build 0% of likely paths. (We have 9% of guards bw, 8% of midpoint bw, and 4% of exit bw = 0% of path bw.)
Jan 21 12:52:03.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 1000/7108, and can only build 0% of likely paths. (We have 15% of guards bw, 15% of midpoint bw, and 11% of exit bw = 0% of path bw.)
Jan 21 12:52:05.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 1113/7108, and can only build 0% of likely paths. (We have 16% of guards bw, 16% of midpoint bw, and 13% of exit bw = 0% of path bw.)
Jan 21 12:52:05.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 1612/7108, and can only build 1% of likely paths. (We have 22% of guards bw, 22% of midpoint bw, and 19% of exit bw = 1% of path bw.)
Jan 21 12:52:06.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 2112/7108, and can only build 2% of likely paths. (We have 29% of guards bw, 29% of midpoint bw, and 24% of exit bw = 2% of path bw.)
Jan 21 12:52:06.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 2611/7108, and can only build 4% of likely paths. (We have 36% of guards bw, 36% of midpoint bw, and 32% of exit bw = 4% of path bw.)
Jan 21 12:52:06.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 3110/7108, and can only build 7% of likely paths. (We have 44% of guards bw, 43% of midpoint bw, and 41% of exit bw = 7% of path bw.)
Jan 21 12:52:06.000 [notice] Bootstrapped 55%: Loading relay descriptors
Jan 21 12:52:06.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 3610/7108, and can only build 11% of likely paths. (We have 49% of guards bw, 49% of midpoint bw, and 48% of exit bw = 11% of path bw.)
Jan 21 12:52:06.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 4109/7108, and can only build 18% of likely paths. (We have 56% of guards bw, 56% of midpoint bw, and 57% of exit bw = 18% of path bw.)
Jan 21 12:52:08.000 [notice] Bootstrapped 62%: Loading relay descriptors
Jan 21 12:52:08.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 4609/7108, and can only build 26% of likely paths. (We have 63% of guards bw, 64% of midpoint bw, and 65% of exit bw = 26% of path bw.)
Jan 21 12:52:09.000 [notice] Bootstrapped 67%: Loading relay descriptors
Jan 21 12:52:09.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 5108/7108, and can only build 36% of likely paths. (We have 70% of guards bw, 70% of midpoint bw, and 73% of exit bw = 36% of path bw.)
Jan 21 12:52:09.000 [notice] Bootstrapped 72%: Loading relay descriptors
Jan 21 12:52:09.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more descriptors: we have 5606/7108, and can only build 47% of likely paths. (We have 77% of guards bw, 77% of midpoint bw, and 78% of exit bw = 47% of path bw.)
Jan 21 12:52:09.000 [notice] Bootstrapped 80%: Connecting to the Tor network
Jan 21 12:52:10.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
Jan 21 12:52:10.000 [notice] Tor has successfully opened a circuit. Looks like client functionality is working.
Jan 21 12:52:10.000 [notice] Bootstrapped 100%: Done
Jan 21 12:52:10.000 [notice] Now checking whether ORPort x.x.x.x:9050 is reachable... (this may take up to 20 minutes -- look for log messages indicating success)
Jan 21 13:11:59.000 [warn] Your server (x.x.x.x:9050) has not managed to confirm that its ORPort is reachable. Relays do not publish descriptors until their ORPort and DirPort are reachable. Please check your firewalls, ports, address, /etc/hosts file, etc.
Jan 21 13:31:59.000 [warn] Your server (x.x.x.x:9050) has not managed to confirm that its ORPort is reachable. Relays do not publish descriptors until their ORPort and DirPort are reachable. Please check your firewalls, ports, address, /etc/hosts file, etc.
Jan 21 13:51:59.000 [warn] Your server (x.x.x.x.:9050) has not managed to confirm that its ORPort is reachable. Relays do not publish descriptors until their ORPort and DirPort are reachable. Please check your firewalls, ports, address, /etc/hosts file, etc.
Jan 21 14:11:59.000 [warn] Your server (x.x.x.:9050) has not managed to confirm that its ORPort is reachable. Relays do not publish descriptors until their ORPort and DirPort are reachable. Please check your firewalls, ports, address, /etc/hosts file, etc.

**Comment by Yawning** [comment]
Not a forum for technical support, though I will say that your bridge line looks wrong.
