### ISSUE TITLE
(theoretical) attack vector: delaying traffic for 1+ seconds?

### ISSUE THREAD

**Issue by SudoHenk** [Yawning/obfs4#22]
Hi,

The spec states that the server computes MAC_C with three variations: E-1,E,E+1 (E = epoch time). I was wondering, would it be possible for an Agent that controls the network to delay initial handshakes of the traffic by >1 seconds to possibly do a denial of service attack?

Should it even be feasable (lets say economicly/tecnically) for an censoring Agent to delay all traffic by 2 seconds (or maybe first try to classify handshakes, and if it cannot be identified delay the connection by two seconds)?

I know this sounds far fetched, but I'm trying to look at feasablitiy of some highly theoretical attacks.

**Comment by Yawning** [comment]
E is hour granular so no.
