### ISSUE TITLE
Can any tcp traffic confusion？可以混淆任何 tcp 流量？

### ISSUE THREAD

**Issue by q158073378252010** [Yawning/obfs4#27]
我想用obfs4proxy混淆 shadowsocks 流量.
I want to use obfs4proxy confusion shadowsocks traffic。

shadowsocks：https://shadowsocks.org/en/index.html

shadowsocks是个代理工具，我想用obfs4来混淆 shadowsocks 的流量以规避 防火长城的审查。
shadowsocks is a proxy tool, I want to confuse shadowsocks obfs4 traffic to circumvent the Great Firewall of review.
请问我该如何做？
Can I do?

**Comment by Yawning** [comment]
Don't know, never used it.  Maybe with one of those random adapter shims that I've seen floating around every time this comes up, but it's not a use case I'm interested in supporting.

**Comment by q158073378252010** [comment]
？

**Comment by q158073378252010** [comment]
@Yawning  ？

**Comment by david415** [comment]
@q158073378252010 don't use shadowsocks, it's amateur software. just use tor pluggable transports, that should be enough for censorship circumvention.
